### ISSUE TITLE
Error on [containers/swag : Populate the dictionary of all containers]

### ISSUE THREAD

**Issue by hpowernl** [notthebee/infra#1]
Have followed the steps in your readme, only run into the following:

`fatal: [home]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'nextcloud'\n\nThe error appears to be in '/home/hpower/infra/roles/containers/swag/tasks/main.yml': line 36, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Populate the dictionary of all containers\n  ^ here\n"
}`

**Comment by notthebee** [comment]
I've just pushed a pretty substantial update
Pull from the repo and try to execute the playbook again
