### ISSUE TITLE
[WARNING]: Could not match supplied host pattern, ignoring: fleet

### ISSUE THREAD

**Issue by ickam** [notthebee/infra#13]
Hi,
I was trying to adapt this repo to my use, but I can't get it to work. I get the "[WARNING]: Could not match supplied host pattern, ignoring: fleet" 
I'm trying to run in locally on my ubuntu vm, so I changed hosts file to 

```
[kombajn]
127.0.0.1  ansible_user=[redacted] ansible_connection=local

```
I tried for the subfolder in the host_vars to be named both "kombajn" and "127.0.0.1", but it doesn't seem to make a difference.
I am a complete noob at ansible, the only playbook that I used in the past is Jeff Geerling's internet-pi, but I hope you can help me.

**Comment by notthebee** [comment]
Replace `- hosts: fleet` with `- hosts: kombajn` in run.yml.
