### ISSUE TITLE
[WARNING]: - ironicbadger.ansible_role_snapraid was NOT installed successfully:

### ISSUE THREAD

**Issue by imadam123** [notthebee/infra#17]
~/infra  ansible-galaxy install -r requirements.yml

Starting galaxy role install process
[WARNING]: - bertvv.samba (v2.7.1) is already installed - use --force to change version to
unspecified
[WARNING]: - geerlingguy.security (2.1.0) is already installed - use --force to change
version to unspecified
[WARNING]: - geerlingguy.ntp (2.3.1) is already installed - use --force to change version to
unspecified
[WARNING]: - geerlingguy.node_exporter (1.0.2) is already installed - use --force to change
version to unspecified
[WARNING]: - chriswayg.msmtp-mailer (master) is already installed - use --force to change
version to unspecified
[WARNING]: - stuvusit.smartd (master) is already installed - use --force to change version
to unspecified
[WARNING]: - oefenweb.dns (v1.1.32) is already installed - use --force to change version to
unspecified
[WARNING]: - notthebee.ubuntu_autoinstall (main) is already installed - use --force to
change version to unspecified
- downloading role 'ansible_role_snapraid', owned by ironicbadger
[WARNING]: - ironicbadger.ansible_role_snapraid was NOT installed successfully: - sorry,
ironicbadger.ansible_role_snapraid was not found on https://galaxy.ansible.com/api/.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

appears that its been removed from the site. tried manually installing it from github but its the same error

**Comment by bamx23** [comment]
It was renamed to [ironicbadger.snapraid](https://galaxy.ansible.com/ironicbadger/snapraid). Also, there is a breaking change: renaming `snapraid_runner_gmail_pass` to `snapraid_runner_email_pass`.
