### ISSUE TITLE
In depth Video

### ISSUE THREAD

**Issue by TrueWLAN** [notthebee/infra#22]
Hi, is it possible to create an in-depth video/documentation about your ansible playbook and if possible make it available for Linux/Windows Subsystem for Linux as well, as these options are more often used than MacOS. Thanks.

**Comment by notthebee** [comment]
A video like that would take months of work, and unfortunately I don't have the time for it.

As I mentioned in a separate issue, the only thing that the playbook requires is Ubuntu 20.04/22.04 on the target machine. Your host machine can run any operating system that you'd like, as long as it can run Ansible.

**Comment by TrueWLAN** [comment]
![chrome_hEo5wWimnG](https://user-images.githubusercontent.com/50050291/180412457-5f733c9f-4104-4652-bb3a-f01ad0ad58ca.png)
Either I am blind, stupid or both, Is there a fire with example variables like the example host file? As I am unable to find it 😞
