### ISSUE TITLE
TASK [network/swag : Populate the dictionary of all containers]

### ISSUE THREAD

**Issue by hpowernl** [notthebee/infra#3]
Installed a Ubuntu 20.04 in Vmware for test, only failed on:

`TASK [network/swag : Populate the dictionary of all containers] ********************************************************
fatal: [home]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'nextcloud'\n\nThe error appears to be in '/home/hpower/infra/tasks/list_services.yml': line 27, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Populate the dictionary of all containers\n  ^ here\n"}`

**Comment by elmuz** [comment]
I am facing the same.

**Comment by elmuz** [comment]
@hpowernl I think the issue is that you need to populate 'subdomains' dictionary var. Have you tried that?

**Comment by notthebee** [comment]
Yep, it's what @elmuz said. The `subdomains` var should look like this:
```
subdomains: {
    'nextcloud': 'nextcloudsubdomain',
    'bitwarden: 'bitwardensubdomain'
}
```
I will put a default value into vars.yml in my next commit.

**Comment by notthebee** [comment]
https://github.com/notthebee/infra/commit/612d2de78e54d3d8864f7662155b78e8e5e07c08#diff-cfae0d4248f7142f7b17f826cd7a519280e312577690e957830d23dcf35a3fffR48
