### ISSUE TITLE
SWAG for internal network

### ISSUE THREAD

**Issue by elmuz** [notthebee/infra#4]
Hi Wolfgang, newbie question. I understood SWAG comes in two instances: one internal with most services supposed to be used in the LAN and one public (eg. nextCloud, authelia, ...). I understand that for the public you need either a personal domain you can validate with cloudflare or a free subdomain (like duckdns) that you can validate with the specific plugin. But what about the internal one? Has to be validated anyway? I see you are using `*.box`, that's fine.
- I was going with `*.server`, I though any name could work, but nginx complains about that not being a valid domain name (i.e. it wants something like domain.com). Is your a compliant one?
- Do we need dns validation even for names used in the lan only?
Thank you in advance

**Comment by notthebee** [comment]
* It should be something along the lines of `homer.*` or `authelia.*`
* I'm using a qualified TLD for my internal services in order to get rid of the HTTPS errors. You can also disble the Let's Encrypt functionality completely if you're ok with local-only domains.
